### ISSUE TITLE
Only first part of name showing in trade pop up

### ISSUE THREAD

**Issue by Pepsai** [Kuba77/Saloon.tf#67]
Instead of "Cafe monster" It says "Cafe"

![6762b365078d1f9058819d92112bf54c](https://cloud.githubusercontent.com/assets/7471079/6931107/baf2fe90-d809-11e4-8163-277f449ce467.png)

**Comment by Kuba77** [comment]
It's intentional, not all team names can fit, so I use two forms normal one and a short, both custom defined :+1:
